//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int BookID { get; set; }
        public string BookIndexImg { get; set; }
        public string BookName { get; set; }
        public string BookDetailsImg { get; set; }
        public string BookDetails { get; set; }
        public double BookPrice { get; set; }
        public string BookRoost { get; set; }
        public int BookStock { get; set; }
    }
}
