//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo01.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public string ProductName { get; set; }
        public decimal MarketPrice { get; set; }
        public decimal SellingPrice { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string Introduction { get; set; }
        public bool IsOnSale { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
    
        public virtual ProductCategory ProductCategory { get; set; }
    }
}
